### ISSUE TITLE
Fails to decode string from manifest

### ISSUE THREAD

**Issue by eybisi** [erev0s/apkInspector#19]
Probably sample have some anti-analysis tricks. 
[infected.zip](https://github.com/erev0s/apkInspector/files/13761881/infected.zip) (password: infected)
```
~ apkInspector -m -apk /tmp/0070BC10699A982A26F6DA48452B8F5E648E1E356A7C1667F393C5C3A1150865.apk
apkInspector Version: 1.1.8
Copyright 2023 erev0s <projects@erev0s.com>

Traceback (most recent call last):
  File "/usr/bin/bin/apkInspector", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/bin/lib/python3.11/site-packages/cli/apkInspector.py", line 109, in main
    manifest = get_manifest(extracted_data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/bin/lib/python3.11/site-packages/apkInspector/axml.py", line 645, in get_manifest
    manifest_object = ManifestStruct.parse(raw_manifest)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/bin/lib/python3.11/site-packages/apkInspector/axml.py", line 469, in parse
    string_pool = StringPoolType.parse(file)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/bin/lib/python3.11/site-packages/apkInspector/axml.py", line 191, in parse
    string_data = cls.read_strings(file, string_offsets, string_pool_header.strings_start, is_utf8)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/bin/lib/python3.11/site-packages/apkInspector/axml.py", line 169, in read_strings
    content = cls.decode_stringpool_mixed_string(file, is_utf8)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/bin/lib/python3.11/site-packages/apkInspector/axml.py", line 128, in decode_stringpool_mixed_string
    u16len = struct.unpack('<H', file.read(2))[0]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
struct.error: unpack requires a buffer of 2 bytes
```

**Comment by nasir-hussain-swat** [comment]
Check if there's an updated version of apkInspector available. Sometimes, newer versions might handle different APK structures more effectively

**Comment by erev0s** [comment]
thank you @eybisi i was looking for this apk to check it.
apkInspector can now handle this edge case fine.
If you are looking to get the manifest (with all the proper values) I would suggest utilizing androguard (just make sure androguard uses the latest version of apkInspector so it can handle it properly)
